version: 1
labels:
  - label: "automerge"
    authors: ["github-actions"]
    files:
      - "build.sbt"
      - "project/Versions.scala"
      - "project/plugins.sbt"
      - "examples\\/.*\\.scala"
  - label: "dependency"
    authors: ["github-actions"]
    files:
      - "build.sbt"
      - "project/Versions.scala"
      - "project/plugins.sbt"
      - "examples\\/.*\\.scala"
